# Generated by Django 6.0.3 on 2026-04-07 00:23

import django.db.models.deletion
from utils.helpers import generar_sku_mejorado
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default=generar_sku_mejorado, max_length=10, unique=True)),
                ('estado_fisico', models.CharField(choices=[('nuevo', 'Nuevo'), ('como_nuevo', 'Como nuevo'), ('bueno', 'Bueno'), ('aceptable', 'Aceptable'), ('con_detalles', 'Con detalles')], max_length=20)),
                ('descripcion_estado', models.TextField(blank=True, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplares', to='inventario.libro')),
            ],
        ),
    ]
