# Generated by Django 6.0.3 on 2026-04-08 02:48

import django.utils.timezone
import utils.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Ejemplar', 'verbose_name_plural': 'Ejemplares'},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='descripcion_estado',
            field=models.TextField(blank=True, help_text='Detalles adicionales del estado', null=True),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='estado_fisico',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('como_nuevo', 'Como nuevo'), ('bueno', 'Bueno'), ('aceptable', 'Aceptable'), ('con_detalles', 'Con detalles')], help_text='Condición física del ejemplar', max_length=20),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de adquisición', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, help_text='Precio de venta al público', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='sku',
            field=models.CharField(db_index=True, default=utils.helpers.generar_sku_mejorado, help_text='Identificador único del ejemplar', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad en inventario'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, help_text='ISBN-10 o ISBN-13', max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='ejemplar',
            index=models.Index(fields=['sku'], name='inventario__sku_dfc4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='ejemplar',
            index=models.Index(fields=['libro'], name='inventario__libro_i_398daa_idx'),
        ),
        migrations.AddIndex(
            model_name='ejemplar',
            index=models.Index(fields=['estado_fisico'], name='inventario__estado__d07c67_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['isbn'], name='inventario__isbn_e7f116_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['categoria'], name='inventario__categor_aeb02a_idx'),
        ),
    ]
