# Generated by Django 6.0.3 on 2026-04-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_categoria_options_alter_ejemplar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. Nuevo, Como nuevo, Aceptable', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de lo que implica este estado', null=True)),
            ],
            options={
                'verbose_name': 'Estado Físico',
                'verbose_name_plural': 'Estados Físicos',
            },
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='nuevo_estado_fisico',
            field=models.ForeignKey(blank=True, help_text='Nueva relación con el modelo EstadoFisico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejemplares', to='inventario.estadofisico'),
        ),
    ]
