# Generated by Django 6.0.3 on 2026-04-21 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_estadofisico_ejemplar_nuevo_estado_fisico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='estado_fisico',
        ),
        migrations.RenameField(
            model_name='ejemplar',
            old_name='nuevo_estado_fisico',
            new_name='estado_fisico',
        ),
    ]
