# Generated by Django 6.0.3 on 2026-04-26 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_inventario__estado__d07c67_idx_inventario__estado__d1afbc_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='edicion',
            new_name='editorial',
        ),
        migrations.AlterField(
            model_name='ejemplar',
            name='estado_fisico',
            field=models.ForeignKey(help_text='Condición física del ejemplar', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ejemplares', to='inventario.estadofisico'),
        ),
        migrations.AddIndex(
            model_name='ejemplar',
            index=models.Index(fields=['estado_fisico'], name='inventario__estado__d1afbc_idx'),
        ),
    ]
