# Generated by Django 6.0.3 on 2026-04-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_rename_edicion_libro_editorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='anio_publicacion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Año de publicación original', null=True),
        ),
    ]
