# Generated by Django 6.0.3 on 2026-04-08 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_categoria_options_alter_ejemplar_options_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['-creado_en'], 'verbose_name_plural': 'Detalles de Venta'},
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='libro',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='ejemplar',
            field=models.ForeignKey(default=1, help_text='Ejemplar específico vendido', on_delete=django.db.models.deletion.PROTECT, to='inventario.ejemplar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio al momento de la venta', max_digits=8),
            preserve_default=False,
        ),
    ]
