# Generated by Django 6.0.3 on 2026-04-08 05:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_categoria_options_alter_ejemplar_options_and_more'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('observaciones', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adquisiciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquisiciones', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Adquisiciones',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAdquisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('adquisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='proveedores.adquisicion')),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adquisiciones', to='inventario.ejemplar')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Adquisicion',
                'ordering': ['creado_en'],
            },
        ),
    ]
