# Generated by Django 6.0.3 on 2026-04-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_adquisicion_detalleadquisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquisicion',
            name='estado',
            field=models.CharField(choices=[('por_inventariar', 'Por inventariar'), ('completado', 'Completado')], default='completado', max_length=20),
        ),
        migrations.AddField(
            model_name='adquisicion',
            name='tipo',
            field=models.CharField(choices=[('identificado', 'Identificado'), ('lote_cerrado', 'Lote cerrado')], default='identificado', help_text='Lote cerrado: cuando recibes una caja sin saber el contenido exacto', max_length=20),
        ),
    ]
