# Generated by Django 6.0.3 on 2026-05-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_adquisicion_tipo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquisicion',
            name='cantidad_libros_lote',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de libros en la caja (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='adquisicion',
            name='codigo_lote',
            field=models.CharField(blank=True, help_text='ID único del lote', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adquisicion',
            name='costo_lote',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de la caja cerrada', max_digits=12, null=True),
        ),
    ]
