# Generated by Django 6.0.3 on 2026-05-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_adquisicion_cantidad_libros_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
