# Generated by Django 6.0.3 on 2026-04-07 00:23

import django.db.models.deletion
import reservas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ticket', models.CharField(default=reservas.models.generar_codigo_unico, max_length=10, unique=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(default=reservas.models.vencimiento_default)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de recolección'), ('completada', 'Completada (Entregada y pagada)'), ('cancelada', 'Cancelada (Tiempo expirado)')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('libros', models.ManyToManyField(to='inventario.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservas y Apartados',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
