# Generated by Django 6.0.3 on 2026-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='ejemplares',
            field=models.ManyToManyField(blank=True, related_name='reservas_activas', to='inventario.ejemplar'),
        ),
    ]
