# Generated by Django 6.0.3 on 2026-04-26 00:43

import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_ejemplares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo_ticket',
            field=models.CharField(default=reservas.models.generar_codigo_unico, max_length=15, unique=True),
        ),
    ]
